//
//  HomeModels.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct IOSTaskModel: Codable {

    var status: String?
    var totalResults: Int?
    var articles: [Articles] = []

    struct Articles: Codable {
        var author: String?
        var title: String?
        var description: String?
        var urlToImage: String?
        var publishedAt: String?
    }
}

struct Profile: Codable {
    var status: Int
    var name: String
}
