//
//  HomeWorker.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol  HomeWorkerProtocol {
    func doLoadAllNewsRequest(apiKey: String, provider: TaskEndPoints) -> Observable<IOSTaskModel>
}

class HomeWorker: HomeWorkerProtocol {

    func doLoadAllNewsRequest(apiKey: String, provider: TaskEndPoints) -> Observable<IOSTaskModel> {
        provider.syncNews(apiKey: apiKey)
    }
}
