//
//  HomePresenter.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresenterInput: class {
    func present(news: IOSTaskModel)
    func present(error: Error)
}

protocol HomePresenterOutput: class {
    func display(section: IOSTaskModel)
    func display(error: Error)
}

class HomePresenter: HomePresenterInput {

    weak var output: HomePresenterOutput?

    func present(news: IOSTaskModel) {
        output?.display(section: news)
    }

    func present(error: Error) {
        output?.display(error: error)
    }
}
